[package]
name = "arcc"
version = "1.0.4"
edition = "2021"

[dependencies.serde]
version = "1.0.203"
features = [ "derive" ]

[dependencies.serde_json]
version = "1.0.117"

[dependencies.arcana-core]
path = "../core"
